export const ACTION_ACTION_START = "ACTION_ACTION_START";
export const ACTION_ACTION_ERROR = "ACTION_ACTION_ERROR";
export const ACTION_EDIT_SUCCESS = "ACTION_EDIT_SUCCESS";
export const ACTION_LOAD_SUCCESS = "ACTION_LOAD_SUCCESS";
export const TODAYACTION_LOAD_SUCCESS = "TODAYACTION_LOAD_SUCCESS";
export const ACTION_ADD_SUCCESS = "ACTION_ADD_SUCCESS";
export const ACTION_DELETE_SUCCESS = "ACTION_DELETE_SUCCESS";
